CREATE TABLE TB_USUARIO (
	ID INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	STATUS INTEGER NOT NULL DEFAULT 1,
	ADM INTEGER NOT NULL DEFAULT 0,
	NOME VARCHAR(150) NOT NULL,
	LOGIN VARCHAR(60) NOT NULL,
	SENHA VARCHAR(60) NOT NULL
);

CREATE TABLE TB_FORMULARIO (
	ID INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	NOME VARCHAR(250) NOT NULL,
	DESCRICAO VARCHAR(250)
);

CREATE TABLE TB_REL_GRUPO (
	ID INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	DESCRICAO VARCHAR(100)
);

CREATE TABLE TB_REL_SUB_GRUPO (
	ID INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	DESCRICAO VARCHAR(100)
);

CREATE TABLE TB_RELATORIO (
	ID INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	NOME VARCHAR(250) NOT NULL,
	DESCRICAO VARCHAR(250),
	ID_GRUPO INTEGER,
	ID_SUB_GRUPO INTEGER,
	FR3 VARCHAR(250),
	FOREIGN KEY(ID_GRUPO) REFERENCES TB_REL_GRUPO(ID),
	FOREIGN KEY(ID_SUB_GRUPO) REFERENCES TB_REL_SUB_GRUPO(ID)
);

CREATE TABLE TB_USU_PERMISSAO (
	ID INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	ID_USU INTEGER NOT NULL,
	ID_FORM INTEGER,
	ID_RELATORIO INTEGER,
	VISUALIZAR INTEGER NOT NULL DEFAULT 1,
	INCLUIR INTEGER NOT NULL DEFAULT 1,
	EXCLUIR INTEGER NOT NULL DEFAULT 1,
	EDITAR INTEGER NOT NULL DEFAULT 1,
	FOREIGN KEY(ID_USU) REFERENCES TB_USUARIO(ID),
	FOREIGN KEY(ID_FORM) REFERENCES TB_FORMULARIO(ID),
	FOREIGN KEY(ID_RELATORIO) REFERENCES TB_RELATORIO(ID)
);

CREATE TRIGGER IF NOT EXISTS TGR_AFT_INSERT_RELATORIO
AFTER INSERT ON TB_RELATORIO
BEGIN
	-- Insere o relatório nas permissões para todos os usuários já como visualizar
    INSERT INTO TB_USU_PERMISSAO (ID_USU, ID_RELATORIO, VISUALIZAR)
    SELECT ID, NEW.ID, 0 FROM TB_USUARIO;
END;

CREATE TRIGGER IF NOT EXISTS TGR_AFT_INSERT_USUARIO
AFTER INSERT ON TB_USUARIO
BEGIN
    -- Insere permissões para cada formulário
    INSERT INTO TB_USU_PERMISSAO (ID_USU, ID_FORM, ID_RELATORIO, VISUALIZAR)
    SELECT NEW.ID, ID, NULL, 0 FROM TB_FORMULARIO;

    -- Insere permissões para cada relatório
    INSERT INTO TB_USU_PERMISSAO (ID_USU, ID_FORM, ID_RELATORIO, VISUALIZAR)
    SELECT NEW.ID, NULL, ID, 0 FROM TB_RELATORIO;
END;
